image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - build
    - release

build:
    stage: build
    script:
        - "dotnet build"

release: 
    stage: release
    script: 
        - "dotnet publish -p:PublishTrimmed=true -p:PublishSingleFile=true -f netcoreapp3.1 -r win-x64 -c Release -o out"
    artifacts:
        paths:
            - out/
        expire_in: 30 days
    only:
        - master
        - tags
